- hosts: localhost
  connection: local
  tasks:
    - name: Install dependencies
      become: true
      become_user: root
      community.general.pacman:
        name:
          - hyprland
          - hyprlock
          - hyprpaper
          - pipewire
          - wireplumber
          - rofi
          - neovim
          - fzf
          - ripgrep
          - waybar
          - swaync
          # screenshots
          - grim
          - slurp

        state: present
